config/routes.rb
Rails.application.routes.draw do
root 'articles#index'

  get '/articles' => 'articles#index'
  get '/articles/new' => 'articles#new'
  get '/articles/:id' => 'articles#show', as: 'articles_show'
  get '/articles/:id/edit' => 'articles#edit', as: 'articles_edit'
  put '/articles/:id' => 'articles#update', as: 'articles_update'
  delete '/articles/:id/delete' => 'articles#delete', as: 'articles_delete'
  post '/articles' => 'articles#create', as: 'articles_create' 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  validates :name, presence: true, uniqueness: true           
  validates :body, presence: true, length: {minimum: 5}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
       @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)

        if @article.valid? 
            @article.save
            redirect_to articles_path
        else
            render :new
        end 
    end

    def show
        @article = Article.find(params[:id])
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:notice] = "The article has been updated successfully"
            redirect_to articles_path
        else
            flash[:notice] = "Meh, something went wrong."
            render :edit
        end
    end

    def delete
        @article = Article.find(params[:id])
        @article.destroy
        flash[:notice] = "Article has been deleted."
        redirect_to articles_path
    
    end

    private 

    def article_params
        params.require(:article).permit(:name, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<div>
<% if @article.errors.any? %>
<h2>Ooops! The article was not saved due to the following errors</h2>
  <ul>
    <% @article.errors.full_messages.each do |message| %>
    <li>
      <%= messages %>
    </li>
    <% end %>
  </ul>
<% end %>
</div>

<%= form_with scope: :article, url: articles_update_path, method: :put do |f| %>

<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div>
  <%= f.label :body %>
  <%= f.text_field :body %>
</div>

<div>
  <%= f.submit %>
</div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% flash.each do |name,messages| %>
<ul>
<li><%= messages %></li>
</ul>
<% end %>

<table>
  <thead>
   <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Body</th>
   </tr>
  </thead>
  <tbody>
   <% @articles.each do |article| %>
     <tr>
      <td><%= article.id %></td>
      <td><%= article.name %></td>
      <td><%= article.body %></td>
      <td><%= link_to 'Show', articles_show_path(article) %></td>
      <td><%= link_to 'Edit', articles_edit_path(article) %></td>
      <td><%= link_to 'Delete', articles_delete_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
     </tr>
   <% end %>
  </tbody>
</table>

<%= link_to 'New Article', articles_new_path %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<div>
<% if @article.errors.any? %>
<h2>Ooops! The Article was not created due to the following errors</h2>
  <ul>
    <% @article.errors.full_messages.each do |message| %>
    <li>
      <%= message %>
    </li>
    <% end %>
  </ul>
<% end %>
</div>

<%= form_with scope: :article, url: articles_create_path do |f| %>

<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div>
  <%= f.label :body %>
  <%= f.text_field :body %>
</div>

<div>
  <%= f.submit %>
</div>
<% end %>

app/views/articles/show.html.erb
<h1>View an Article</h1>

<p>Post ID: <%= @article.id %></p>
<p>Title: <%= @article.name %></p>
<p>Body: <%= @article.body %></p>


<%= link_to 'Back', articles_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Jaren Cudilla', articles_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
       <%= link_to "Article List", articles_path %>
       <%= link_to "Create Article", articles_new_path %>
       <%= link_to "About", "https://jarencudilla.github.io" %>
       <%= link_to "Projects", "https://jarencudilla.github.io" %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
  <title>Rails activity - Blog App</title>
   <%= csrf_meta_tags %>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 </head>
<body>
<%= render 'layouts/navigation' %>

<% flash.each do |name,messages| %>
<ul>
<li><%= messages %></li>
</ul>
<% end %>
<%= yield %>
  </body>
</html>